version: '3'
services:
  #=======FrontEnd=======
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    networks:
      app_net:
        ipv4_address: 172.16.238.3
    volumes:
      - ./frontend/src:/app/src
  #=======Microservicio usuario=======
  usuarios-bd: #base de datos usuarios
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db_users
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  microservicio-usuario: #microservicio usuarios
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes: #borrar cuando este configurado por completo
      - ./graphql:/app
    networks:
      app_net:
        ipv4_address: 172.16.238.15
    depends_on:
      - usuarios-bd
  #=======Microservicio Productos=======
  catalogo-bd: #base de datos catalogo
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db_products
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306" 
    networks:
      app_net:
        ipv4_address: 172.16.238.20
  microservicio-catalogo: #microservicio catalogo
    build:
      context: ./products/gql
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
    networks:
      app_net:
        ipv4_address: 172.16.238.25
    depends_on:
      - catalogo-bd 
  #=======Microservicio =======
  #=======Gateway Nestjs=======
  gateway:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      #- "4000:4000"
    networks:
      app_net:
        ipv4_address: 172.16.238.2
    depends_on:
      - microservicio-usuario
      - microservicio-catalogo
  #=======RabbitMQ=======
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672" 
      - "15672:15672"
    hostname: stats
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      app_net:
        ipv4_address: 172.16.238.5
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
volumes:
  data: {}